import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from src.models import StudentRequestDomainModel


class PDFEngine:
    """PDF generation engine creating official digital approval certificates using ReportLab."""

    @classmethod
    def generate_approval_certificate(cls, request: StudentRequestDomainModel) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()
        
        # Custom Paragraph Styles
        title_style = ParagraphStyle(
            'HeaderTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1a237e'),
            alignment=1, # Center
            spaceAfter=6
        )

        subtitle_style = ParagraphStyle(
            'HeaderSub',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#555555'),
            alignment=1,
            spaceAfter=20
        )

        section_heading = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#0d47a1'),
            spaceBefore=14,
            spaceAfter=8
        )

        body_style = ParagraphStyle(
            'BodyTextCustom',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#333333')
        )

        elements = []

        # Header Title & Subtitle
        elements.append(Paragraph("UNIVERSITY ADMINISTRATIVE SERVICES", title_style))
        elements.append(Paragraph("Official Digital Request Approval Certificate • CampusDesk AI Engine", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#1a237e'), spaceAfter=15))

        # Certificate Details Table
        status_str = request.status.value.replace('_', ' ').title()
        table_data = [
            [Paragraph("<b>Request ID:</b>", body_style), Paragraph(request.request_id, body_style)],
            [Paragraph("<b>Student Name:</b>", body_style), Paragraph(request.student_name, body_style)],
            [Paragraph("<b>Student / Roll ID:</b>", body_style), Paragraph(request.student_id or "N/A", body_style)],
            [Paragraph("<b>Category:</b>", body_style), Paragraph(request.category.value, body_style)],
            [Paragraph("<b>Decision Status:</b>", body_style), Paragraph(f"<font color='#2e7d32'><b>{status_str}</b></font>", body_style)],
            [Paragraph("<b>Approved Amount:</b>", body_style), Paragraph(f"₹{request.amount_inr:,.2f}" if request.amount_inr > 0 else "N/A", body_style)],
            [Paragraph("<b>Issue Date:</b>", body_style), Paragraph(request.created_at.strftime("%B %d, %Y %H:%M UTC"), body_style)]
        ]

        t = Table(table_data, colWidths=[150, 350])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8f9fa')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e0e0e0')),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))

        elements.append(t)
        elements.append(Spacer(1, 15))

        # Request Summary Section
        elements.append(Paragraph("Executive Request Summary", section_heading))
        elements.append(Paragraph(request.summary, body_style))
        elements.append(Spacer(1, 12))

        # Original Request Section
        elements.append(Paragraph("Submitted Text Baseline", section_heading))
        elements.append(Paragraph(f"<i>\"{request.raw_text}\"</i>", body_style))
        elements.append(Spacer(1, 25))

        # Verification Footer
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e0e0e0'), spaceAfter=10))
        footer_text = (
            "<b>Verifiable Digital Record Notice:</b> This certificate was programmatically generated by CampusDesk AI "
            "Backend Engine. The corresponding execution record has been written to the Notion System Run Log database."
        )
        elements.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, leading=11, textColor=colors.HexColor('#666666'))))

        # Build PDF document
        doc.build(elements)
        pdf_data = buffer.getvalue()
        buffer.close()
        return pdf_data
