from src.models import StudentRequestDomainModel, DraftedResponse, WorkflowStatus


class ResponseDrafterAgent:
    """Agent responsible for drafting official university emails and PDF approval letters."""

    @classmethod
    def draft(cls, request: StudentRequestDomainModel, approver_notes: str = "") -> DraftedResponse:
        status_text = request.status.value.replace("_", " ").title()
        
        if request.status in (WorkflowStatus.AUTO_APPROVED, WorkflowStatus.APPROVED):
            subject = f"✅ APPROVED: {request.title} [{request.request_id}]"
            
            html_body = f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
                <h2 style="color: #2e7d32; border-bottom: 2px solid #2e7d32; padding-bottom: 8px;">CampusDesk AI — Formal Approval Notice</h2>
                <p>Dear <strong>{request.student_name}</strong> (Roll #{request.student_id or 'N/A'}),</p>
                <p>Your request has been officially <strong>APPROVED</strong>.</p>
                
                <div style="background-color: #f1f8e9; padding: 12px; border-left: 4px solid #2e7d32; margin: 16px 0;">
                    <p style="margin: 4px 0;"><strong>Request ID:</strong> {request.request_id}</p>
                    <p style="margin: 4px 0;"><strong>Category:</strong> {request.category.value}</p>
                    <p style="margin: 4px 0;"><strong>Status:</strong> {status_text}</p>
                    <p style="margin: 4px 0;"><strong>Summary:</strong> {request.summary}</p>
                    {"<p style='margin: 4px 0;'><strong>Approved Amount:</strong> ₹" + f"{request.amount_inr:,.2f}" + "</p>" if request.amount_inr > 0 else ""}
                </div>

                {"<p><strong>Approver Remarks:</strong> " + approver_notes + "</p>" if approver_notes else ""}

                <p>Please find attached your official digital Approval Certificate (PDF).</p>
                <br>
                <p style="color: #666; font-size: 12px;">This is an automated operational notice generated by CampusDesk AI System Engine.</p>
            </div>
            """
            
            pdf_content = (
                f"OFFICIAL APPROVAL CERTIFICATE\n"
                f"----------------------------------------\n"
                f"Request ID: {request.request_id}\n"
                f"Student Name: {request.student_name}\n"
                f"Student ID / Roll: {request.student_id or 'N/A'}\n"
                f"Category: {request.category.value}\n"
                f"Decision Status: APPROVED\n"
                f"Approved Amount: ₹{request.amount_inr:,.2f}\n"
                f"Duration: {request.duration_days} Day(s)\n"
                f"Issued Date: {request.created_at.strftime('%Y-%m-%d %H:%M UTC')}\n\n"
                f"Summary:\n{request.summary}\n\n"
                f"Verification Note: This document is programmatically signed and logged in the University Administrative Control Center."
            )
            
        else:
            subject = f"❌ REJECTED: {request.title} [{request.request_id}]"
            
            html_body = f"""
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
                <h2 style="color: #c62828; border-bottom: 2px solid #c62828; padding-bottom: 8px;">CampusDesk AI — Formal Status Update</h2>
                <p>Dear <strong>{request.student_name}</strong> (Roll #{request.student_id or 'N/A'}),</p>
                <p>We regret to inform you that your request has been <strong>REJECTED</strong> after administrative review.</p>
                
                <div style="background-color: #ffebee; padding: 12px; border-left: 4px solid #c62828; margin: 16px 0;">
                    <p style="margin: 4px 0;"><strong>Request ID:</strong> {request.request_id}</p>
                    <p style="margin: 4px 0;"><strong>Category:</strong> {request.category.value}</p>
                    <p style="margin: 4px 0;"><strong>Reason:</strong> {request.decision_reason}</p>
                </div>

                {"<p><strong>Approver Remarks:</strong> " + approver_notes + "</p>" if approver_notes else ""}

                <p>If you wish to appeal this decision, please contact your department office directly.</p>
                <br>
                <p style="color: #666; font-size: 12px;">CampusDesk AI System Engine</p>
            </div>
            """
            
            pdf_content = (
                f"OFFICIAL STATUS NOTICE\n"
                f"----------------------------------------\n"
                f"Request ID: {request.request_id}\n"
                f"Student Name: {request.student_name}\n"
                f"Decision Status: REJECTED\n"
                f"Reason: {request.decision_reason}"
            )

        return DraftedResponse(
            email_subject=subject,
            email_body_html=html_body,
            pdf_letter_content=pdf_content
        )
